USE [master]
GO

/****** Object:  Database [Diagnostic]    Script Date: 4/7/2023 1:16:07 PM ******/
CREATE DATABASE [Diagnostic]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Diagnostic', FILENAME = N'E:\MSSQL11.MSSQLSERVER\MSSQL\DATA\Diagnostic.mdf' , SIZE = 20480KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Diagnostic_log', FILENAME = N'F:\MSSQL11.MSSQLSERVER\MSSQL\Log\Diagnostic_log.ldf' , SIZE = 4224KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Diagnostic].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Diagnostic] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Diagnostic] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Diagnostic] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Diagnostic] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Diagnostic] SET ARITHABORT OFF 
GO

ALTER DATABASE [Diagnostic] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Diagnostic] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Diagnostic] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Diagnostic] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Diagnostic] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Diagnostic] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Diagnostic] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Diagnostic] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Diagnostic] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Diagnostic] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Diagnostic] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Diagnostic] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Diagnostic] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Diagnostic] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Diagnostic] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Diagnostic] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Diagnostic] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Diagnostic] SET RECOVERY FULL 
GO

ALTER DATABASE [Diagnostic] SET  MULTI_USER 
GO

ALTER DATABASE [Diagnostic] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Diagnostic] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Diagnostic] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Diagnostic] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [Diagnostic] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Diagnostic] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Diagnostic] SET  READ_WRITE 
GO

