<<<<<<< HEAD
/****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP (1000) [SrvName]
      ,[DBname]
      ,[dbid]
      ,[status]
      ,[crdate]
      ,[cmptlevel]
      ,[collation_name]
      ,[user_access_desc]
      ,[is_read_only]
      ,[is_auto_close]
      ,[is_auto_shrink]
      ,[state]
      ,[is_in_standby]
      ,[is_clean_shutdown]
      ,[is_loggin_enabled]
      ,[snapshot_state_desc]
      ,[is_read_commit]
      ,[recovery_model_desc]
      ,[page_verify_desc]
      ,[is_auto_create_stats]
      ,[is_auto_update_stats]
      ,[is_encrypted]
      ,[is_db_chain]
      ,[is_trustworthy_on]
  FROM [DBA_REP].[dbo].[tblDBAdatabases]
=======
/****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP (1000) [SrvName]
      ,[DBname]
      ,[dbid]
      ,[status]
      ,[crdate]
      ,[cmptlevel]
      ,[collation_name]
      ,[user_access_desc]
      ,[is_read_only]
      ,[is_auto_close]
      ,[is_auto_shrink]
      ,[state]
      ,[is_in_standby]
      ,[is_clean_shutdown]
      ,[is_loggin_enabled]
      ,[snapshot_state_desc]
      ,[is_read_commit]
      ,[recovery_model_desc]
      ,[page_verify_desc]
      ,[is_auto_create_stats]
      ,[is_auto_update_stats]
      ,[is_encrypted]
      ,[is_db_chain]
      ,[is_trustworthy_on]
  FROM [DBA_REP].[dbo].[tblDBAdatabases]
>>>>>>> master
  where dbname = 'KVPROD'