USE [master]
GO


ALTER DATABASE BI360LSS_Archive SET RECOVERY Full WITH NO_WAIT 
ALTER DATABASE BI360HUD06_Archive SET RECOVERY Full WITH NO_WAIT 
ALTER DATABASE BI360HUD09_Archive SET RECOVERY Full WITH NO_WAIT 
ALTER DATABASE BI360HUD12_Archive SET RECOVERY Full WITH NO_WAIT 
ALTER DATABASE BI360HUD76_Archive SET RECOVERY Full WITH NO_WAIT 
ALTER DATABASE BI360HUD77_Archive SET RECOVERY Full WITH NO_WAIT 
ALTER DATABASE BI360HUD78_Archive SET RECOVERY Full WITH NO_WAIT 
ALTER DATABASE CustomArea SET RECOVERY Full WITH NO_WAIT 
ALTER DATABASE Solver_Scheduler SET RECOVERY Full WITH NO_WAIT 
ALTER DATABASE solver_repository SET RECOVERY Full WITH NO_WAIT 
ALTER DATABASE BI360LSS SET RECOVERY Full WITH NO_WAIT 





